development:
  adapter: postgresql
  encoding: unicode
  database: dafanfgl4e086n
  pool: 2
  username: fzkhgnzqiegvhz
  password: 7ede47178ef23ef790d2d99b6d46b9ea9c88a2172670f36202abc1dc85017339
  host: ec2-34-227-120-79.compute-1.amazonaws.com
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>